import streamlit as st
import requests
import os
# Page Configuration
st.set_page_config(
    page_title="Customer Segmentation Tool",
    page_icon="🛒",
    layout="wide"
)

# Constants
# 'api' refers to the docker service name defined in docker-compose.yml
API_URL = os.getenv("API_URL", "http://localhost:8000")

# Header
st.title("E-Commerce Customer Segmentation")
st.markdown("""
This tool uses a Machine Learning model (K-Means) to classify customers based on their buying behavior.
Enter the customer metrics below to get insights.
""")

st.divider()

# Input Form
with st.container():
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("Customer Metrics")
        recency = st.number_input(
            "Recency (Days since last purchase)", 
            min_value=0, 
            value=30,
            help="How many days ago was the customer's last order?"
        )
        
        frequency = st.number_input(
            "Frequency (Total number of orders)", 
            min_value=1, 
            value=5,
            help="How many separate invoices has this customer generated?"
        )

    with col2:
        st.subheader("Financial Metrics")
        monetary = st.number_input(
            "Monetary Value (Total Spend $)", 
            min_value=0.0, 
            value=500.0,
            step=10.0,
            help="Total revenue generated by this customer."
        )
        
        unique_products = st.number_input(
            "Unique Products Purchased", 
            min_value=1, 
            value=10,
            help="Diversity of the customer's catalog."
        )

# Prediction Button
if st.button("Analyze Customer Segment", type="primary"):
    payload = {
        "Recency": recency,
        "Frequency": frequency,
        "Monetary": monetary,
        "Unique_Products": unique_products
    }
    
    with st.spinner("Analyzing customer behavior..."):
        try:
            full_url = f"{API_URL}/predict"
            response = requests.post(full_url, json=payload)
            
            
            if response.status_code == 200:
                result = response.json()
                segment = result['segment_name']
                cluster_id = result['cluster_id']
                
                st.success("Analysis Complete!")
                
                # Display Results
                st.subheader(f"Segment: {segment}")
                st.write(f"Cluster ID: {cluster_id}")
                
                if cluster_id == 1:
                    st.balloons()
                    st.info("Strategy: Provide loyalty rewards and early access to new products.")
                elif cluster_id == 0:
                    st.warning("Strategy: This customer is at risk. Send a re-engagement campaign.")
                else:
                    st.info("Strategy: Upsell specific items to increase monetary value.")
                    
            else:
                st.error("Error: Could not retrieve prediction from API.")
                st.write(response.text)
                
        except requests.exceptions.ConnectionError:
            st.error("Connection Error: Is the API container running?")